// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ExecQuery(arg1:string,arg2:string):Promise<main.ExecQueryResponse>;

export function GetTableData(arg1:string,arg2:string,arg3:number):Promise<main.GetTableDataResponse>;

export function GetTableInfo(arg1:string,arg2:string):Promise<main.TableInfo>;

export function GetTableNames(arg1:string):Promise<main.DbTablesResponse>;

export function OpenFile():Promise<main.OpenFileResponse>;

export function ShowWrongFileTypeMessage():Promise<void>;
