// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExecQuery(arg1, arg2) {
  return window['go']['main']['App']['ExecQuery'](arg1, arg2);
}

export function GetTableData(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetTableData'](arg1, arg2, arg3);
}

export function GetTableInfo(arg1, arg2) {
  return window['go']['main']['App']['GetTableInfo'](arg1, arg2);
}

export function GetTableNames(arg1) {
  return window['go']['main']['App']['GetTableNames'](arg1);
}

export function OpenFile() {
  return window['go']['main']['App']['OpenFile']();
}

export function ShowWrongFileTypeMessage() {
  return window['go']['main']['App']['ShowWrongFileTypeMessage']();
}
